# Generated by Django 5.1.1 on 2024-10-18 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0001_initial'),
        ('section', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='section',
            constraint=models.UniqueConstraint(fields=('grade', 'section'), name='unique_grade_section'),
        ),
    ]
